version: '3.3'

networks:
  user-management-network-v2:
    driver: bridge

services:
  # PHP + Laravel
  user-management-laravel-v2:
    container_name: user-management-laravel-v2
    image: devilbox/php-fpm:8.2-work
    tty: true
    restart: on-failure
    expose:
      - 9000
    volumes:
      - ../:/app
    working_dir: /app
    networks:
      - user-management-network-v2
    depends_on:
      - user-management-db-v2

  # MySQL
  user-management-db-v2:
    container_name: user-management-db-v2
    image: mysql:latest
    tty: true
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - user-management-network-v2
    environment:
      MYSQL_ROOT_PASSWORD: "!r00t-pa55w0rd!"
    volumes:
      - ./local/services/mysql/entrypoint.d/:/docker-entrypoint-initdb.d/

  # Nginx
  user-management-server-v2:
    container_name: user-management-server-v2
    image: nginx:stable
    tty: true
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - user-management-network-v2
    volumes:
      - ../:/app
      - ./local/services/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - user-management-laravel-v2

  # NodeJS
  user-management-node-js-v2:
    container_name: user-management-node-js-v2
    image: node:16.3.0
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
    networks:
      - user-management-network-v2
    working_dir: /app
    build:
      context: ../
      dockerfile: ./docker/local/services/nodejs/Dockerfile
